"""initial

Revision ID: e41b0fbcf540
Revises: 
Create Date: 2026-05-26 14:30:29.392979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41b0fbcf540'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('image', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='productstatus'), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('purchase_limit', sa.Integer(), nullable=True),
    sa.Column('profit_type', sa.Enum('fixed', 'percentage', name='profittype'), nullable=False),
    sa.Column('profit_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_method', sa.Enum('manual', 'auto', name='profitmethod'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('claim_reset', sa.Enum('midnight', 'purchase', name='claimreset'), nullable=False),
    sa.Column('balance_source', sa.Enum('balance', 'balance_deposit', name='balancesource'), nullable=False),
    sa.Column('purchase_rabat_l1', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('purchase_rabat_l2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('purchase_rabat_l3', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('purchase_rabat_l4', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('purchase_rabat_l5', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_rabat_l1', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_rabat_l2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_rabat_l3', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_rabat_l4', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_rabat_l5', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('specific', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('balance_deposit', sa.BigInteger(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('referral_by', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
